Add contact app [WIP]
onespacemedia/project-template pull request #271
Opened 2018-05-09 16:47 UTC by daniel-clayton

Needs testing.

2018-05-15 10:01 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/contact/models.py
> +
You'll probably want to add a content type icon here. See https://github.com/onespacemedia/cms-icons/

2018-06-05 10:03 UTC, lewiscollard requested changes

2018-06-05 10:03 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/contact/admin.py
> +        patterns = super(ContactSubmissionAdmin, self).get_urls()
You should prefer the simpler Python 3 `super()` form here.

2018-06-05 10:03 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/contact/models.py
> +    hero_kicker = models.CharField(
As these are rendered in a "Hero" fieldset, you should give this a `verbose_name` of 'kicker'.

2018-06-05 10:03 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/contact/models.py
> +    form_email_address = models.CharField(
Same applies for these form_* fields here as applied to the hero - as they're contained in a fieldset called "Form" the default rendering of "Form email address" is redundant.

2018-06-05 10:03 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/contact/models.py
> +    form_email_address = models.CharField(
Also, unless you are planning on making this accept multiple email addresses separated by something, you should make this an EmailField.

On the other hand, if you are planning on that, put a method on the content type to do this splitting.

2018-06-05 10:03 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/contact/models.py
> +    success_page_title = models.CharField(
Same comments apply re: fieldset titles above - give this a simpler `verbose_name`.

2018-06-05 10:03 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/contact/models.py
> +        help_text='If this is left blank it will use the page title',
This `help_text` does not match the behaviour of the template.

2018-06-05 10:03 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/contact/models.py
> +        help_text='If this is left blank it will use the page title',
Also, punctuate `help_text`s as sentences.

2018-06-05 10:03 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/contact/models.py
> +        help_text='This is the email address form submissions will be sent to.',
Minor grammatical nitpick, but I'd prefer the simpler wording of "Form submissions will be sent to this email address."

2018-06-07 10:24 UTC, lewiscollard requested changes

2018-06-07 10:24 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/contact/models.py
> +    def get_email_addresses(self):
Properties should normally be named as if they are instance attributes. Either name this `email_addresses` or keep the existing name and make it a normal function.

2018-06-07 10:24 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/contact/admin.py
> +        for email in self.get_email_addresses:
`self.get_email_addresses` is not a property or attribute of `ContactSubmissionAdmin`.

2018-07-04 12:38 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/contact/models.py
> +            email.strip()
This does nothing; `.strip()` does not modify in place. A unit test should have caught this.

2018-07-04 12:40 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/contact/models.py
> +            email.strip()
Easier: `re.split('[\s,]+', self.form_email_address)`

2018-07-04 12:41 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/contact/models.py
> +        verbose_name='Email Address',
We never use Title Case.

2018-08-03 15:36 UTC, lewiscollard commented
I am setting a bad example, but I've rebased and force-pushed to clean up the history of this one. Hopefully I did not murder anything.

2018-08-10 15:16 UTC, lewiscollard approved these changes

2018-08-23 12:38 UTC, AidanCurrah commented
Since we're adding the landing hero macro in this PR, should we change the other pages to use the macro-ized hero?

2018-10-08 15:43 UTC, merged