Add columns Post CSS function for on grid width calculations
onespacemedia/project-template pull request #300
Opened 2018-09-28 15:58 UTC by joe-hastings

Add a Post CSS function that gives on grid width calculations for neater CSS so we don't need to have the long calc all over our code.

2018-09-28 16:08 UTC, joe-hastings commented
I suppose I could also go through and replace all the places widths that should be on grid are used to use this?

2018-11-05 17:13 UTC, lewiscollard requested changes

2018-11-05 17:13 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/gulpfile.js/lib/postCssProcessors.js
> +      columns: function (n, t, gutter) {
Can you change `n` and `t` to a full English word?

2018-11-06 13:53 UTC, joe-hastings reviewed
It's a bit odd how we use 8 columns at `--sm` and 12 at `--md`, we don't really tend to do this in new projects its always 12 all the way down to mobile, might be worth updating this?

2018-11-06 14:14 UTC, lewiscollard commented
Feel free to change that @joe-hastings, if you want. All but one of these are `width: columns(6, 8);`, which can be expressed as `columns(9, 12)` anyway.

2018-11-06 14:21 UTC, joe-hastings commented
> Feel free to change that @joe-hastings, if you want. All but one of these are `width: columns(6, 8);`, which can be expressed as `columns(9, 12)` anyway.

Cool think I will cause it's just easier to see whats going on at a quick glance, I can't be doing complex arithmetic like that on the spot ;)

2018-11-06 15:23 UTC, lewiscollard approved these changes

2018-11-06 15:23 UTC, merged