Add password reset functionality
onespacemedia/project-template pull request #340
Opened 2019-10-29 16:10 UTC by daniel-clayton

- Makes the emails app a mandatory app

2019-10-29 16:15 UTC, lewiscollard requested changes

2019-10-29 16:15 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/emails/templates/emails/password-reset.html
> +    <li>Close and restart your browser, and ideally clear your cache, cookies and history, before attempting to log in with your new password.</li>
You should never need to do this. Clearing cookies is a last resort, and the browser history makes no difference.

2019-10-29 16:15 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/users/templates/users/reset/password_reset_complete.html
> +  <p class="ath-Form_Message">Your password has been reset. You can now <a href="/admin/login/">log in</a> again.</p>
Don't assume where the admin login form lives - `{% url %}` it.

2019-10-29 16:15 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/urls.py
> +    url(r'^admin/reset-password/$', reset_views.ProjectPasswordResetView.as_view(), name='password_reset'),
Break these out into a urlconf in the `users` app, IMO.

2019-10-29 16:15 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/static/admin/auth/login.css
> +/*
Was this file included accidentally?

2019-10-29 16:34 UTC, daniel-clayton commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/static/admin/auth/login.css
> +/*
It has the form styles that are used

2019-10-29 16:38 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/static/admin/auth/login.css
> +/*
OK, some parts are extremely similar to the `auth/login.css` in `osm-jet`. Is there a case for moving it there?

2019-10-30 09:59 UTC, daniel-clayton commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/urls.py
> +    url(r'^admin/reset-password/$', reset_views.ProjectPasswordResetView.as_view(), name='password_reset'),
Would it not be a bit strange that some `/admin/` urls go through the users app and some don't?

2019-10-30 10:03 UTC, daniel-clayton commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/urls.py
> +    url(r'^admin/reset-password/$', reset_views.ProjectPasswordResetView.as_view(), name='password_reset'),
Then again so do the social urls

2019-10-30 10:10 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/urls.py
> +    url(r'^admin/reset-password/$', reset_views.ProjectPasswordResetView.as_view(), name='password_reset'),
I don't think it is any aesthetically weirder, and having a separate urlconf would keep app-specific URL routes within the app.

2019-10-30 10:14 UTC, daniel-clayton commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/urls.py
> +    url(r'^admin/reset-password/$', reset_views.ProjectPasswordResetView.as_view(), name='password_reset'),
kdoke, but I'm not going to use a namespace because it would involve doing a bunch of overrides

2019-10-30 10:28 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/emails/templates/emails/password-reset.html
> +{% extends 'emails/base.html' %}
Django convention is to use underscores to separate words in template names. This pull request uses dashes inconsistently, too.

2019-10-30 10:29 UTC, lewiscollard commented on {{cookiecutter.repo_name}}/{{cookiecutter.package_name}}/apps/emails/templates/emails/password-reset.html
> +{% extends 'emails/base.html' %}
^^ I think you may have pushed up the fix for this one about five seconds before I wrote this comment :)

2019-10-31 10:53 UTC, lewiscollard approved these changes

2019-10-31 10:53 UTC, merged